{
 "title": "Thousand Eyes Grafana Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DOM Load Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"domLoadTime\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Page Load Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pageLoadTime\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTime\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Agent-Aggregated Response time (ms)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dnsTime\" or r[\"_field\"] == \"sslTime\" or r[\"_field\"] == \"waitTime\" or r[\"_field\"] == \"connectTime\")\n  |> group(columns: [\"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 5, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"responseCode\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Time (response + receive) in ms",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"totalTime\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avgLatency\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Loss ( % of packets not reaching destination)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"loss\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Average Number of Hops",
   "type": "bargauge",
   "description": "Number of hops for path trace to destination",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg_numberOfHops\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Jitter (standard deviation of latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"jitter\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Average Response Time (RTT of the path trace to the destination)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensordata_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"2236549\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg_responseTime\")\n  |> group(columns: [\"agentName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}